### ISSUE TITLE
다중 서명 플로우 서명하기 UI 추가

### ISSUE THREAD

**Issue by jay-noncelab** [noncelab/coconut_wallet#26]
# 🚀 Feature - 서명하기 UI 추가 

### 📝 Description

---

다중 서명 플로우 서명하기 과정에서 필요한 UI를 추가합니다.

### ✅ To Do List

---

- [ ] 서명하기 UI 추가
- [ ] 기존 스캔, 스캔정보 확인 스크린과 연결
- [ ] 테스트 케이스 추가

### 📚Etc

---

**Comment by Ella-noncelab** [comment]
저랑 피오가 할당된거 잘못된건가요?

**Comment by jay-noncelab** [comment]
> 저랑 피오가 할당된거 잘못된건가요?

잘못 생성된 이슈입니다
