### ISSUE TITLE
거래 자세히 보기, UTXO 상세화면

### ISSUE THREAD

**Issue by pio-noncelab** [noncelab/coconut_wallet#43]
# 🚀 Feature - 거래 자세히 보기, UTXO 상세화면

### 📝 Description

---

input/output 리스트 연동, UTXO 상세화면의 앱바 Tooltip 구현
멤풀 링크 연결
### ✅ To Do List

---

- [x] 거래 자세히 보기 - input/output 리스트 연동
- [x] UTXO 상세화면 - input/output 리스트 연동
- [x] 앱바 Tooltip 구현
- [x] 멤풀 링크 연결

**Comment by Ella-noncelab** [comment]
input, output 카드에서 내 지갑 주소로 들어온 utxo가 가장 상단에 보이도록 하기

**Comment by Ella-noncelab** [comment]
uxto 상세 - 트랜잭션 ID - 거래 자세히 보기 버튼 이벤트 없음
